#!/usr/bin/php
<?php

register_shutdown_function( "fatal_handler" );

function fatal_handler() {
  $errfile = "unknown file";
  $errstr  = "shutdown";
  $errno   = E_CORE_ERROR;
  $errline = 0;

  $error = error_get_last();

  if( $error !== NULL) {
    $errno   = $error["type"];
    $errfile = $error["file"];
    $errline = $error["line"];
    $errstr  = $error["message"];
  }

  debug( $errno .  $errstr . $errfile .  $errline  );
}


require "Trader.class.php";

define("FILE_LOG", "log");

@unlink(FILE_LOG);
$file = @fopen (FILE_LOG, "a");

function debug($str)
{
	global $file;

	@fputs($file, $str);
}

fscanf(STDIN, "%d\n", $start_capital);
fscanf(STDIN, "%d\n", $total_days);
debug("Entree : Capital : $start_capital\nDays: $total_days\n\n");

$trader = new Trader;

$trader->start_capital = intval($start_capital);
$trader->total_days = intval($total_days);
$trader->left_days = intval($total_days);
$trader->days_past = 1;
$trader->values = array();

while (1)
{
	$line = trim(fgets(STDIN));
	if ($line == "--END--" || $line == "--end--")
		return;
	$trader->values[] = intval($line);
	$answer = $trader->get_decision();
	$trader->left_days--;
	$trader->days_past++;
	debug("Entree : $line\nReponse : $answer\n\n");
	echo  "$answer\n";


}
?>